---
# yaml-language-server: $schema=https://docs.mergify.com/mergify-configuration-schema.json

# Renovate pull requests are deliberately created as drafts. Once a maintainer promotes a pull request for review, these
# rules ensure that only Renovate, or the n3t.uk terraform-docs bot, has changed the branch, and that they are
# up-to-date, before Mergify approves and merges it.

merge_protections_settings:
  reporting_method: check-runs
  auto_merge_conditions:
    - author=renovate[bot]
    - -draft
    - -conflict
    - -closed

pull_request_rules:
  - name: Automatic approval for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - base=main
      - "#commits-behind=0"
      - -draft
      - -conflict
      - -closed
      - or:
          - commits[*].author==renovate[bot]
          - commits[*].author==n3tuk-terraform-docs[bot]
    actions:
      review:
        type: APPROVE
