---
# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
extends: default

ignore:
  # Ignore anything related to Kiro as these are machine-generated files and should not be validated by yamllint.
  - .kiro/**

rules:
  document-start:
    present: true
  document-end:
    present: false

  empty-lines:
    max: 1
    max-start: 0
    max-end: 0

  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation: {}

  indentation:
    spaces: consistent
    indent-sequences: true
    # Taskfiles use variable indentations on multi-line strings for the
    # documentation and in-line scripting
    check-multi-line-strings: false

  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  brackets:
    forbid: non-empty

  braces:
    forbid: non-empty

  float-values:
    forbid-nan: true
    require-numeral-before-decimal: true

  quoted-strings:
    quote-type: double
    required: only-when-needed
    allow-quoted-quotes: true

  trailing-spaces: {}

  truthy:
    allowed-values:
      - "true"
      - "false"
    check-keys: false
