---
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

output: prefixed
interval: 3s

set:
  # Enforce the pipefail option in the Bash library to ensure the failure of any one step in the pipeline fails all.
  - pipefail

# NOTE: The `flatten` option is used when including other Taskfiles to ensure that the tasks are included at the
#       top-level of this Taskfile. This is important to allow tasks in the included Taskfiles to be called directly
#       from other imported Taskfiles, simplifying the overall structure of the Taskfiles and allowing for a more
#       modular approach to task management.

includes:
  utils:
    taskfile: .task/utils.yaml
    flatten: true
  prettier:
    taskfile: .task/prettier.yaml
    flatten: true
  yamllint:
    taskfile: .task/yamllint.yaml
    flatten: true
  markdownlint:
    taskfile: .task/markdownlint.yaml
    flatten: true
  check-jsonschema:
    taskfile: .task/check-jsonschema.yaml
    flatten: true
  actionlint:
    taskfile: .task/actionlint.yaml
    flatten: true
  zizmor:
    taskfile: .task/zizmor.yaml
    flatten: true
  snyk:
    taskfile: .task/snyk.yaml
    flatten: true

tasks:
  default:
    desc: Run the linting, formatting, analysis, and documentation tasks
    summary: |-
      Run the linting, formatting, analysis, and documentation tasks for these GitHub Workflows, and associated files.
      Use the following command for additional information on the steps involved:

        $ task --summary develop
    silent: true
    cmds:
      - task: develop

  develop:
    aliases:
      - d
      - dev
    desc: Run the linting, formatting, analysis, and documentation tasks
    summary: |-
      Run the linting, formatting, analysis, and documentation tasks for these GitHub Workflows, and associated files.

      The `develop` task is designed to run the core integration steps for this repository (and can do so continuously
      when using the `--watch` option). It is designed to be run during development to ensure that any changes made to
      the code are valid, correctly formatted, and do not introduce any security issues or misconfigurations.

      Specifically, it will format and lint all supported files, run static code analysis tools, test the code, and keep
      the documentation up-to-date, where it is automated.
    deps:
      - task: utils:pre-commit
      - task: utils:pre-checks
    silent: true
    watch: true
    cmds:
      - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
      - task: lint
      - task: formatting
      - task: analyse
      - cmd: echo -e '\e[0;32mCompleted\e[0m'

  formatting:
    aliases:
      - f
    desc: Format the selected files within this repository
    summary: |-
      Re-format the selected files within this repository to ensure they are consistent in their layout and usage,
      including running all Markdown, YAML, JSON, and TOML files through Prettier.
    silent: true
    cmds:
      - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
      - task: prettier
      - cmd: echo -e '\e[0;32mCompleted\e[0m'

  lint:
    aliases:
      - l
    desc: Lint selected files within this repository
    summary: |-
      Run linting checks across all Terraform, YAML, and Markdown files to find any potential issues or inconsistencies
      within the code.
    silent: true
    cmds:
      - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
      - task: yamllint
      - task: markdownlint
      - cmd: echo -e '\e[0;32mCompleted\e[0m'

  analyse:
    desc: Run static analysis checks for this repository
    summary: |-
      Run static code analysis tools (i.e Snyk) against these GitHub Workflows, as well zizmor and actionlint against
      the GitHub Dependabot configuration, and all GitHub Workflow files, to identify any potential security issues and
      misconfigurations within the code.
    silent: true
    cmds:
      - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
      - task: actionlint
      - task: zizmor
      - task: snyk
      - cmd: echo -e '\e[0;32mCompleted\e[0m'

  clean:
    aliases:
      - c
    desc: Clean temporary files from the repository and configurations
    summary: |-
      Clean any temporary directories and files created by both this Taskfile, and the tools and applications called
      from it, and from within the configurations.
    run: once
    silent: true
    cmds:
      - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
      - cmd: rm -f .prettiercache
      - cmd: rm -rf .task/checksum
      - cmd: echo -e '\e[0;32mCompleted\e[0m'
