---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Build Release
run-name: >-
  Updating GitHub Release tags for ${{ github.ref_name || github.sha }}

concurrency:
  group: ${{ github.repository }}:build-release
  # Ensure all tags are updated in sequence
  cancel-in-progress: false

on:
  push:
    tags:
      - v*.*.*

# No permissions by default
permissions: {}

defaults:
  run:
    # Error handling and pipefile must be explicitly set via the default shell
    #   https://github.com/actions/runner/issues/353#issuecomment-1067227665
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  update-tags:
    name: Update Major/Minor Tags
    runs-on: ubuntu-latest
    permissions:
      contents: write # write the tags back to the repository

    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # zizmor: ignore[artipacked] # This action must support git push to commit the tags back to the repository.
          persist-credentials: true

      - name: Fetch the tags
        run: git fetch --force --tags

      - name: Force update the major tag
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          VERSION=${TAG#v}
          MAJOR=${VERSION%%.*}
          git tag "v${MAJOR}" "${TAG}" -f
          git push origin "refs/tags/v${MAJOR}" -f

      - name: Force update the major/minor tag
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          VERSION=${TAG#v}
          MAJOR_MINOR=${VERSION%.*}
          git tag "v${MAJOR_MINOR}" "${TAG}" -f
          git push origin "refs/tags/v${MAJOR_MINOR}" -f
