---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Draft Release
run-name: >-
  Building draft GitHub Release for ${{ github.sha }}

concurrency:
  group: ${{ github.repository }}:draft-release
  # All releases are created from-scratch, so we can terminate mid-process
  cancel-in-progress: true

on:
  push:
    branches:
      - main

# No permissions by default
permissions: {}

jobs:
  draft-release:
    name: Draft the Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # create a release
      pull-requests: read # read the pull requests to build release
    outputs:
      release-id: ${{ steps.release-drafter.outputs.release-id }}
      release-url: ${{ steps.release-drafter.outputs.release-url }}
      release-tag: ${{ steps.release-drafter.outputs.release-tag }}

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Draft the release
        id: release-drafter
        # yamllint disable-line rule:line-length
        uses: release-drafter/release-drafter@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yaml
